accounts/urls.py

from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^house/$', views.user_profile, name='user_profile'),
	url(r'^login/$', views.user_login, name='user_login'),
	url(r'^demo-login/$', views.demo_login, name='demo_login'),
	url(r'^logout/$', views.user_logout, name='user_logout'),
	url(r'^register/$', views.register_user, name='register_user'),
]

budget/urls.py

from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^new_budget/', views.create_budget, name='create'),
	url(r'^manage_budget/', views.manage_budget, name='manage'),
	url(r'^new_expense/', views.new_expense, name='new_expense'),
	url(r'^expense/(?P<expense_id>[0-9]+)/', views.expense_detail, name='expense_detail'),
	url(r'^expense/(?P<expense_id>[0-9]+)/', views.approve_expense, name='approve_expense'),
]

feed/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^announce/$', views.make_announcement, name='announce'),
	url(r'^get-viewed/$', views.get_viewed, name='get-viewed'),
	url(r'^view-post/$', views.view_post, name='view-post'),
	url(r'^submit-post/$', views.submit_post, name='submit-post'),
	url(r'^refresh-feed/$', views.get_recent_posts_ajax, name='refresh-feed'),
	url(r'^get-announcements/$', views.get_announcements, name='get-announcements'),
]

neighborhood/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
	url(r'^home/$', views.neighborhood_home, name='home'),
	url(r'^status/$', views.neighborhood_status, name='status'),
	url(r'^index/$', views.index, name='index'),
	url(r'^details/$', views.neighborhood_details, name='details'),
	url(r'^get-neighborhoods/$', views.get_neighborhoods, name='get_neighborhoods'),
	url(r'^get-event/$', views.get_event, name='get_event'),
	url(r'^current-calendar/$', views.get_current_calendar, name='current_calendar'),
	url(r'^specific-calendar/$', views.get_specific_calendar, name='specific_calendar'),
	url(r'^new-event/$', views.new_event, name='new-event'),
]

neighbors/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts.views import user_login

urlpatterns = [
	url(r'^$', user_login, name='index'),
	url(r'^neighborhood/', include('neighborhood.urls', namespace="neighborhood")),
	url(r'^account/', include('accounts.urls', namespace="accounts")),
	url(r'^budget/', include('budget.urls', namespace="budget")),
	url(r'^discussions/', include('discussions.urls', namespace="discussions")),
	url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^markers/', include('markers.urls', namespace="markers")),
	url(r'^feed/', include('feed.urls', namespace="feed")),
	url(r'^admin/', include(admin.site.urls)),
]

budget/models.py
from django.db import models
from django.utils import timezone
from neighborhood.models import Neighborhood

import datetime


class Budget(models.Model):
	id = models.AutoField(primary_key=True)
	title = models.CharField(max_length=60, default='Community Budget',verbose_name="Budget Title")
	total_funds = models.DecimalField(max_digits=14, decimal_places=2, default=0.00, verbose_name="Total Funds")
	total_expenses = models.DecimalField(max_digits=14, decimal_places=2, default=0.00, verbose_name="Total Expenses")
	residence_fee = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Residence Fee", default=10.00)
	create_date = models.DateTimeField(default=timezone.now, verbose_name="Created on")
	neighborhood = models.ForeignKey(Neighborhood)

	def __str__(self):
		return self.title


"""
	EXPENSE CLASS
	Expenses are a cost charge to be added to the budget upon
	approval.

	TO BE ADDED
	- split into RECURRING and SINGLE-TIME classes to inherit
	from standing Expense class.
"""
class Expense(models.Model):
	IMPROVEMENT = 'IMP'
	REPAIR = 'REP'
	RECREATION = 'REC'
	FEE = 'FEE'
	OTHER = 'OTH'
	EXPENSE_TYPES = (
		(IMPROVEMENT, 'Improvement'),
		(REPAIR, 'Repair'),
		(RECREATION, 'Recreation'),
		(FEE, 'Fee'),
		(OTHER, 'Other'),
	)
	types = models.CharField(max_length=3, choices=EXPENSE_TYPES, default=REPAIR)
	id = models.AutoField(primary_key=True)
	title = models.CharField(max_length=60, default='Expense',verbose_name="Expense Title")
	description = models.TextField(verbose_name="Description", default="Description of why and how this expense is needed")
	cost = models.DecimalField(max_digits=12, decimal_places=2)
	create_date = models.DateTimeField(default=timezone.now, verbose_name="Created on")
	start_date = models.DateTimeField(verbose_name="Starts on")
	end_date = models.DateTimeField(verbose_name="Ends on")
	type = models.CharField(max_length=50, verbose_name='Type of Expense')
	approved = models.BooleanField(default=False)
	budget = models.ForeignKey(Budget)

	def __str__(self):
		return self.title

	def approve(self):
		self.approved = True

	def unapprove(self):
		self.approved = False

	def was_recently_approved(self):
		now = timezone.now()
		return now - datetime.timedelta(days=5) <= self.create_date <= now

budget/forms.py
from .models import Budget, Expense
from django import forms


class BudgetForm(forms.ModelForm):

	class Meta:
		model = Budget
		fields = (
			'title',
			'residence_fee',
			'neighborhood',
		)


class ExpenseForm(forms.ModelForm):

	class Meta:
		model = Expense
		fields = (
			'title',
			'description',
			'cost',
			'start_date',
			'end_date',
			'types',
			'budget',
		)

budget/views.py
from django.shortcuts import render, get_object_or_404, \
	HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from neighborhood.models import Neighborhood

from .forms import BudgetForm, ExpenseForm
from .models import Budget, Expense



@login_required
def create_budget(request):
	"""
	---CREATE BUDGET---
	This is the view passed to the user when their neighborhood does not
	have a budget already attached to it. Uses a Django form to get input
	from user and create the budget
	:param request
	"""
	neighborhood = request.user.userprofile.house.neighborhood
	if request.method == 'POST':
		budget_form = BudgetForm(request.POST)
		if budget_form.is_valid():
			budget_form.neighborhood = neighborhood
			budget = budget_form.save()
			budget.neighborhood = neighborhood
			budget.save()
		return HttpResponseRedirect('/budget/manage_budget/')
	else:
		budget_form = BudgetForm()
	return render(request, 'budget/create_budget.html', {'budget_form': budget_form})


@login_required
def manage_budget(request):
	"""
	---MANAGE BUDGET---
	This is the view passed to the user when their neighborhood has a viewable
	budget. It displays the attributes of a Budget model in addition to the list
	of expenses with a budget_id attr matching the current budget.id
	:param request
	"""
	try:
		neighborhood = request.user.userprofile.house.neighborhood
		budget = Budget.objects.get(neighborhood=neighborhood)
		request.session['budget_id'] = budget.id
		expense_list = Expense.objects.filter(budget=budget).order_by('-create_date')
	except ObjectDoesNotExist:
		return HttpResponseRedirect('/budget/new_budget/')
	except NameError:
		return render(request, 'budget/manage_budget.html', {'budget': budget})
	return render(request, 'budget/manage_budget.html', {'budget': budget,
														 'expense_list': expense_list} )


@login_required
def new_expense(request):
	"""
	---NEW EXPENSE---
	This is the view passed to the user when they wish to create a new
	expense to be added to the budget once approved. It uses a Django
	form to create the new expense object.
	:param request
	"""
	neighborhood = request.user.userprofile.house.neighborhood
	budget = Budget.objects.get(neighborhood=neighborhood)
	if request.method == 'POST':
		expense_form = ExpenseForm(request.POST)
		if expense_form.is_valid():
			expense = expense_form.save()
			expense.budget = budget
			expense.save()
			return HttpResponseRedirect('/neighborhood/status/')
	else:
		expense_form = ExpenseForm()
	return render(request, 'budget/new_expense.html', {'expense_form': expense_form})


@login_required
def expense_detail(request, expense_id):
	"""
	---EXPENSE DETAIL---
	This is the view passed to the user when they select an expense
	from the expense list displayed on the budget home page. It displays
	the attributes of the expense object to the user.
	:param request
	:param expense_id
	"""
	expense = get_object_or_404(Expense, pk=expense_id)
	if request.method == 'POST':
		expense.approve()
		expense.save()
	return render(request, 'budget/expense_detail.html', {'expense': expense})


@login_required
def approve_expense(request, expense_id):
	"""
	---APPROVE EXPENSE---
	Approve a previously created expense
	:param request
	:param expense_id
	"""
	expense = get_object_or_404(Expense, pk=expense_id)
	expense.approve()
	return render(request, 'budget/expense_detail.html', {'expense': expense})

budget/templates/budget/create_budget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Neighbors</title>
</head>
<body>
    {% if neighborhood.has_budget %}
        <p><strong>You're neighborhood already has a budget!</strong></p>
        <a href="{% url 'budget:manage' %}">View Budget</a>
    {% else %}
    <form id="budget_form" action="{% url 'budget:create' %}" method="post"
            enctype="multipart/form-data">
        {% csrf_token %}
        {{ budget_form.as_p }}
        <input type="submit" name="submit" value="Create Budget"/>
    </form>
    {% endif %}
</body>
</html>

budget/templates/budget/expense_detail.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Neighbors</title>
</head>
<body>
    <div>
        <h1>{{ expense.title }}</h1>
        <p>Cost: {{ expense.cost }}</p>
        <p>Starts: {{ expense.start_date }}</p>
        <p>Ends: {{ expense.end_date }}</p>
        <p>Type: {{ expense.type }}</p>
        <p>Description: {{ expense.description }}</p>
        <p>Status: {{ expense.approved }}</p>

        <p>
        <form action="{% url 'budget:expense_detail' expense.id %}" method="post">
        {% csrf_token %}
            <input type="submit" value="Approve"></a>
        </form>
        </p><br />
        <p><a href="{% url 'budget:manage' %}">Return to Budget</a></p>
    </div>
</body>
</html>

budget/templates/budget/manage_budget.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'neighborhood/css/home.css' %}" />
    <meta charset="UTF-8">
    <title>Neighbors</title>
</head>
<body>

    <div class="jumbotron">
        <div class="container">
            <h1>Welcome to the Neighborhood!</h1>
            <p>{{ neighborhood.division_title }} Division</p>
        </div>
    </div>

    <div class="nav">
        <div class="container">
            <ul class="nav nav-pills">
                <li><a href="{% url 'neighborhood:neighborhood_home' %}">Home</a></li>
                <li><a class="active" href="{% url 'polls:index' %}">Polls</a></li>
				<li><a href="{% url 'discussions:index' %}">Discussions</a></li>
                <li><a href="{% url 'budget:manage' %}">Budget</a></li>
                <li><a href="{% url 'neighborhood:about' %}">About Neighbors</a></li>
                <li><a href="{% url 'accounts:user_profile' %}">Manage Account</a></li>
                <li><a href="{% url 'accounts:user_logout' %}">Sign out</a></li>
            </ul>
        </div>
    </div>

    <div class="content">
        <div class="container">
            <h1>{{ budget.title }}</h1>
            <p>Neighborhood: {{ budget.neighborhood }}</p>
            <p>Total Funds: {{ budget.total_funds }}</p>
            <p>Total Expenses: {{ budget.total_expenses }}</p>
            <p>Residence Fee: {{ budget.residence_fee }}</p>
            <p>Creation Date: {{ budget.create_date }}</p>

            <h3>Expenses</h3>
            <p>
                {% if expense_list %}
                    {% for expense in expense_list %}
                        <p><a href="{% url 'budget:expense_detail' expense.id %}">{{ expense.title }}</a>
                            cost={{ expense.cost }} : approved={{ expense.approved }}</p>
                    {% endfor %}
                {% endif %}
            </p>

            <a href="{% url 'budget:new_expense' %}"><input type="button" value="New Expense"></a><br />


        </div>
    </div>

    <div class="footer">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<h3>About</h3>
					<p>Info/links regarding Neighbors information.</p>
				</div>
				<div class="col-md-4">
					<h3>Contact</h3>
					<p>Info/links for contacting Neighbors peeps</p>
				</div>
				<div class="col-md-4">
					<h3>Help</h3>
					<p>Help and FAQ shit.</p>
				</div>
			</div> <!-- end row -->
		</div> <!-- end container -->
	</div> <!-- end footer -->

</body>
</html>

budget/templates/budget/new_expense.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Neighbors</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'neighborhood/css/map_home.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'budget/style.css' %}"/>
</head>
<body>
<div class="nav">
    <h1 class="white-text">Neighbors</h1>
    <div class="options">
        <a class="btn btn-info" href="{% url 'neighborhood:home' %}"><strong>map</strong></a>
        <a class="btn btn-info" href="{% url 'neighborhood:status' %}"><strong>status</strong></a>
    </div>
    <div class="icons">
        <a id="account" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-user'></span>
        </a>
        <a id="account-menu" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-envelope'></span>
        </a>
        <a id="list" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-list'></span>
        </a>
    </div>
</div>

<div class="content">
    <div class="container col-md-4 col-md-offset-4 ">
        <h1 class="orange-text">New Expense</h1>
        <form id="expense_form" action="{% url 'budget:new_expense' %}" method="post"
                enctype="multipart/form-data">
            {% csrf_token %}
            {{ expense_form.as_p }}
            <input class='btn btn-default' type="submit" name="submit" value="Create Expense"/>
        </form>
        <a href="{% url 'neighborhood:home' %}">Return</a>
    </div>
</div>


</body>
</html>