accounts/urls.py

from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^house/$', views.user_profile, name='user_profile'),
	url(r'^login/$', views.user_login, name='user_login'),
	url(r'^demo-login/$', views.demo_login, name='demo_login'),
	url(r'^logout/$', views.user_logout, name='user_logout'),
	url(r'^register/$', views.register_user, name='register_user'),
]

budget/urls.py

from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^new_budget/', views.create_budget, name='create'),
	url(r'^manage_budget/', views.manage_budget, name='manage'),
	url(r'^new_expense/', views.new_expense, name='new_expense'),
	url(r'^expense/(?P<expense_id>[0-9]+)/', views.expense_detail, name='expense_detail'),
	url(r'^expense/(?P<expense_id>[0-9]+)/', views.approve_expense, name='approve_expense'),
]

feed/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^announce/$', views.make_announcement, name='announce'),
	url(r'^get-viewed/$', views.get_viewed, name='get-viewed'),
	url(r'^view-post/$', views.view_post, name='view-post'),
	url(r'^submit-post/$', views.submit_post, name='submit-post'),
	url(r'^refresh-feed/$', views.get_recent_posts_ajax, name='refresh-feed'),
	url(r'^get-announcements/$', views.get_announcements, name='get-announcements'),
]

neighborhood/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
	url(r'^home/$', views.neighborhood_home, name='home'),
	url(r'^status/$', views.neighborhood_status, name='status'),
	url(r'^index/$', views.index, name='index'),
	url(r'^details/$', views.neighborhood_details, name='details'),
	url(r'^get-neighborhoods/$', views.get_neighborhoods, name='get_neighborhoods'),
	url(r'^get-event/$', views.get_event, name='get_event'),
	url(r'^current-calendar/$', views.get_current_calendar, name='current_calendar'),
	url(r'^specific-calendar/$', views.get_specific_calendar, name='specific_calendar'),
	url(r'^new-event/$', views.new_event, name='new-event'),
]

neighbors/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts.views import user_login

urlpatterns = [
	url(r'^$', user_login, name='index'),
	url(r'^neighborhood/', include('neighborhood.urls', namespace="neighborhood")),
	url(r'^account/', include('accounts.urls', namespace="accounts")),
	url(r'^budget/', include('budget.urls', namespace="budget")),
	url(r'^discussions/', include('discussions.urls', namespace="discussions")),
	url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^markers/', include('markers.urls', namespace="markers")),
	url(r'^feed/', include('feed.urls', namespace="feed")),
	url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^new/$', views.new_poll, name='new'),
	url(r'^(?P<pk>[0-9]+)/$', views.polls_index_detail, name='detail'),
	url(r'^fetch-poll/$', views.get_poll, name='get_poll'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^poll-vote/$', views.poll_vote, name='poll-vote'),
	url(r'^get-votes/$', views.get_votes, name='get-votes')
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

from neighborhood.models import Neighborhood
from accounts.models import User


class Question(models.Model):
	id = models.AutoField(primary_key=True)
	question_text = models.CharField(max_length=200)
	description = models.TextField(max_length=500, default="Default question description")
	pub_date = models.DateTimeField('date published', default=timezone.now)
	neighborhood = models.ForeignKey(Neighborhood, null=True)
	creator = models.ForeignKey(User, null=True)
	is_yes_no = models.BooleanField(default=False)

	def __str__(self):  # __unicode__ on Python 2
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published Recently?'

	def as_dict(self):
		return {
			'question_text': self.question_text,
			'description': self.description,
			'pub_date': str(self.pub_date.date()),
		}


class Choice(models.Model):
	question = models.ForeignKey(Question, null=True)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):  # __unicode__ on Python 2
		return self.choice_text


class Vote(models.Model):
	question = models.ForeignKey(Question, null=True)
	choice = models.ForeignKey(Choice, null=True)
	user = models.ForeignKey(User, null=True)
	time = models.DateTimeField(default=timezone.now)

	class Meta:
		unique_together = (('user','choice'),)


class Poll(models.Model):
	id = models.AutoField(primary_key=True)
	question_text = models.CharField(max_length=400)
	description = models.TextField(max_length=1000, default="Default question description")
	status = models.CharField(max_length=20, default='TBD')
	creator = models.ForeignKey(User, null=True)
	neighborhood = models.ForeignKey(Neighborhood, null=True)
	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.question_text

	def get_confirm_count(self):
		return VotePoll.objects.filter(poll=self, status='CONFIRM').length


class VotePoll(models.Model):
	id = models.AutoField(primary_key=True)
	poll = models.ForeignKey(Poll, null=True)
	choice = models.CharField(max_length=20)
	user = models.ForeignKey(User, null=True)
	time = models.DateTimeField(auto_now=True)

polls/forms.py
from django import forms

from .models import Question, Choice, Poll


class QuestionForm(forms.ModelForm):

	class Meta:
		model = Question
		fields = (
			'question_text',
		)


class ChoiceForm(forms.ModelForm):

	class Meta:
		model = Choice
		fields = (
			'choice_text',
		)


class PollForm(forms.ModelForm):

	class Meta:
		model = Poll
		fields = (
			'question_text',
			'description'
		)

polls/views.py
from accounts.models import Activity
from django.shortcuts import render, get_object_or_404, HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.forms import formset_factory
from django.contrib.auth.decorators import login_required
import json

from neighborhood.models import Neighborhood

from .models import Question, Choice, Vote, VotePoll, Poll
from .forms import QuestionForm, ChoiceForm, PollForm
from feed.models import Feed, FeedPost


class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""
		Return the last five published questions (not including
		those set to be in the future).
		"""
		return Question.objects.filter(
			pub_date__lte=timezone.now()
		).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
		"""
		Excludes any questions that aren't published yet.
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'


@login_required
def new_poll(request):
	if request.method == 'POST':
		# Validate the poll topic Question and Choices
		poll_form = PollForm(request.POST)
		if poll_form.is_valid():
			neighborhood = request.user.userprofile.house.neighborhood
			# Save question_form and create Question object
			poll = poll_form.save()
			poll.neighborhood = neighborhood
			poll.creator = request.user
			poll.save()
			if poll.id is not None:
				# create feedpost to post this new poll to the neighborhood feed
				feed = Feed.objects.get(neighborhood=neighborhood)
				feedpost = FeedPost(text=poll.question_text, user=request.user,
									type='POLL', feed=feed, decision=poll)
				feedpost.save()

				# create activity for user profile
				activity = Activity(activity_type='POLL-CREATE', user=request.user, assoc_obj_id=poll.id)
				activity.save()
				return HttpResponseRedirect('/neighborhood/home')
		else:
			return HttpResponse("Poll is not valid")


# @login_required
# def new_question(request):
# 	ChoiceFormSet = formset_factory(ChoiceForm, extra=2)
# 	if request.method == 'POST':
# 		# Validate the poll topic Question and Choices
# 		question_form = QuestionForm(request.POST)
# 		choice_formset = ChoiceFormSet(request.POST)
# 		if question_form.is_valid() and choice_formset.is_valid():
# 			neighborhood = get_object_or_404(Neighborhood, pk=request.session['neighborhood_id'])
# 			# Save question_form and create Question object
# 			question = question_form.save()
# 			question.neighborhood = neighborhood
# 			question.creator = request.user
# 			question.save()
# 			# Save each choice form into Choice object
# 			for choice_form in choice_formset:
# 				choice = choice_form.save()
# 				choice.question = question
# 				choice.save()
#
# 			# create feedpost to post this new poll to the neighborhood feed
# 			feed = Feed.objects.get(neighborhood=neighborhood)
# 			feedpost = FeedPost(title=question.question_text, user=request.user,
# 								type='POLL', feed=feed, poll=question)
# 			feedpost.save()
# 			return HttpResponseRedirect('/neighborhood/home')
# 			# choice_form.is_valid() failed
# 		# question_form.is_valid() failed
# 		else:
# 			return HttpResponse("Poll topic is not valid")
# 	# not a request.POST
# 	# create blank forms to return
# 	else:
# 		question_form = QuestionForm()
# 		choice_formset = ChoiceFormSet()
# 	return render(request, 'polls/new_poll.html', {'question_form': question_form,
# 												   'choice_formset': choice_formset})


@login_required
def polls_index_detail(request, pk):
	question_list = Question.objects.filter(
		pub_date__lte=timezone.now()
	).order_by('-pub_date')
	selected_question = get_object_or_404(Question, pk=pk)
	return render(request, 'polls/detail.html', {'selected_question': selected_question,
												   'question_list': question_list})


@login_required()
def get_poll(request):
	if request.method == 'GET' and request.is_ajax():
		poll = get_object_or_404(Question, pk=request.GET['id'])
		poll_dict = poll.as_dict()
		return HttpResponse(json.dumps({'poll': poll_dict}), content_type='application/json')


@login_required
def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the question voting form
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice",
		})
	else:
		vote_obj, created = Vote.objects.get_or_create(user=request.user,
												   question=question,
												   choice=selected_choice)
		if not created:
			return HttpResponse("You sneaky buggah! You already voted!")
		else:
			selected_choice.votes += 1
			selected_choice.save()
			# Always return an HttpResponseRedirect after successfully dealing
			# with POST data. This prevents data from being posted twice if a
			# user hits the Back button.
			return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


@login_required
def poll_vote(request):
	if request.method == 'POST' and request.is_ajax():
		vote_choice = request.POST['vote']
		poll_id = request.POST['poll_id']
		print('********SERVER RECEIVED VOTE FOR POLL: ' + poll_id + '********')
		poll = get_object_or_404(Poll, pk=poll_id)
		vote, created = VotePoll.objects.get_or_create(choice=vote_choice,
						user=request.user,
						poll=poll)
		if created:
			activity = Activity(activity_type='POLL-VOTE', user=request.user, assoc_obj_id=vote.id)
			activity.save()
			return HttpResponse(json.dumps({'vote_id': vote.id}), content_type='application/json')
	return HttpResponse(json.dumps({'vote_id': -1}), content_type='application/json')


@login_required
def get_votes(request):
	if request.method == 'GET' and request.is_ajax():
		poll = Poll.objects.get(id=request.GET['poll_id'])
		total_votes = VotePoll.objects.filter(poll=poll).__len__()
		confirm_votes = VotePoll.objects.filter(poll=poll, choice='CONFIRM').__len__()
		deny_votes = VotePoll.objects.filter(poll=poll, choice='DENY').__len__()
		return HttpResponse(json.dumps({'total_count': total_votes,
										'confirm_count': confirm_votes,
										'deny_count': deny_votes}), content_type='application/json')

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <title>Neighbors</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'neighborhood/css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/detail.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'polls/slide.js' %}"></script>

</head>
<body>


<div class="nav">
    <h1 class="white-text">Neighbors</h1>
    <div class="options">
        <a class="btn btn-info" href="{% url 'neighborhood:home' %}"><strong>map</strong></a>
        <a class="btn btn-info" href="{% url 'neighborhood:status' %}"><strong>status</strong></a>
    </div>
    <div class="icons">
        <a id="account" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-user'></span>
        </a>
        <a id="account-menu" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-envelope'></span>
        </a>
        <a id="list" class='btn btn-default btn-circle btn-lg' href="{% url 'neighborhood:details' %}">
            <span class='glyphicon glyphicon-list'></span>
        </a>
        <a id="report" class='btn btn-default btn-circle btn-lg'>
            <span class='glyphicon glyphicon-alert'></span>
        </a>
    </div>
</div>

<div class="content">
    <div class="holder">
        <div class="row col-md-12">
            <div class="col-md-3">
            {% if question_list %}
                {% for question in question_list %}
                    <div class="poll-item-container">
                        <a href="{% url 'polls:detail' question.id %}">
                            <div class="poll-item">

                                    <h1>{{ question.question_text }}</h1>
                                <small>{{ question.pub_date }}</small>
                            </div>
                        </a>
                    </div>

                {% endfor %}
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
            </div>
            <div id="poll-container" class="col-md-9">
                <div class="poll-detail">
                    <h1>{{ selected_question.question_text }}</h1>
                    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{%  endif %}
                    <form action="{% url 'polls:vote' selected_question.id %}" method="post">
                        {% csrf_token %}
                        {% for choice in selected_question.choice_set.all %}
                            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
                            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
                        {% endfor %}
                        <input id='vote' type="submit" value="vote" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'neighborhood/css/home.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <meta charset="UTF-8">
    <title>Neighbors</title>
</head>
<body>

    <div class="jumbotron">
        <div class="container">
            <h1>Welcome to the Neighborhood!</h1>
            <p>{{ neighborhood.division_title }} Division</p>
        </div>
    </div>

    <div class="nav">
        <div class="container">
            <ul class="nav nav-pills">
                <li><a href="{% url 'neighborhood:neighborhood_home' %}">Home</a></li>
                <li><a class="active" href="{% url 'polls:index' %}">Polls</a></li>
				<li><a href="{% url 'discussions:index' %}">Discussions</a></li>
                <li><a href="{% url 'budget:manage' %}">Budget</a></li>
                <li><a href="{% url 'neighborhood:about' %}">About Neighbors</a></li>
                <li><a href="{% url 'accounts:user_profile' %}">Manage Account</a></li>
                <li><a href="{% url 'accounts:user_logout' %}">Sign out</a></li>
            </ul>
        </div>
    </div>

    <div class="content">
        <div class="container">
            <h1>Polls</h1>
        {% if latest_question_list %}
            <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
            <a href="{% url 'polls:new' %}"><input type="button" name="new_poll" value="New Poll"></a><br />
        </div>
    </div>

    <div class="footer">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<h3>About</h3>
					<p>Info/links regarding Neighbors information.</p>
				</div>
				<div class="col-md-4">
					<h3>Contact</h3>
					<p>Info/links for contacting Neighbors peeps</p>
				</div>
				<div class="col-md-4">
					<h3>Help</h3>
					<p>Help and FAQ shit.</p>
				</div>
			</div> <!-- end row -->
		</div> <!-- end container -->
	</div> <!-- end footer -->

polls/templates/polls/new_poll.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Neighbors</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'neighborhood/css/map_home.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
</head>
<body>

<div class="nav">
    <h1 class="white-text">Neighbors</h1>
    <div class="options">
        <a class="btn btn-info" href="{% url 'neighborhood:home' %}"><strong>map</strong></a>
        <a class="btn btn-info" href="{% url 'neighborhood:status' %}"><strong>status</strong></a>
    </div>
    <div class="icons">
        <a id="account" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-user'></span>
        </a>
        <a id="account-menu" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-envelope'></span>
        </a>
        <a id="list" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-list'></span>
        </a>
    </div>
    </a>
</div>
<div class="content">
    <div class="container col-md-2 col-md-offset-5 ">
        <h1>New Poll</h1>
        <form name="poll_form" action="{% url 'polls:new' %}" method="post">
            {% csrf_token %}
            {{ question_form.as_p }}
            {{ choice_formset.as_p }}
            <input class='btn btn-default' type="submit" name="submit" value="Create">
        </form>
        <a href="{% url 'neighborhood:home' %}">Return</a>
    </div>
</div>



</body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

<p>
    <a href="{% url 'polls:index' %}">Back to Polls</a>
</p>