accounts/urls.py

from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^house/$', views.user_profile, name='user_profile'),
	url(r'^login/$', views.user_login, name='user_login'),
	url(r'^demo-login/$', views.demo_login, name='demo_login'),
	url(r'^logout/$', views.user_logout, name='user_logout'),
	url(r'^register/$', views.register_user, name='register_user'),
]

feed/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^announce/$', views.make_announcement, name='announce'),
	url(r'^get-viewed/$', views.get_viewed, name='get-viewed'),
	url(r'^view-post/$', views.view_post, name='view-post'),
	url(r'^submit-post/$', views.submit_post, name='submit-post'),
	url(r'^refresh-feed/$', views.get_recent_posts_ajax, name='refresh-feed'),
	url(r'^get-announcements/$', views.get_announcements, name='get-announcements'),
]

neighborhood/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
	url(r'^home/$', views.neighborhood_home, name='home'),
	url(r'^status/$', views.neighborhood_status, name='status'),
	url(r'^index/$', views.index, name='index'),
	url(r'^details/$', views.neighborhood_details, name='details'),
	url(r'^get-neighborhoods/$', views.get_neighborhoods, name='get_neighborhoods'),
	url(r'^get-event/$', views.get_event, name='get_event'),
	url(r'^current-calendar/$', views.get_current_calendar, name='current_calendar'),
	url(r'^specific-calendar/$', views.get_specific_calendar, name='specific_calendar'),
	url(r'^new-event/$', views.new_event, name='new-event'),
]

neighbors/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts.views import user_login

urlpatterns = [
	url(r'^$', user_login, name='index'),
	url(r'^neighborhood/', include('neighborhood.urls', namespace="neighborhood")),
	url(r'^account/', include('accounts.urls', namespace="accounts")),
	url(r'^budget/', include('budget.urls', namespace="budget")),
	url(r'^discussions/', include('discussions.urls', namespace="discussions")),
	url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^markers/', include('markers.urls', namespace="markers")),
	url(r'^feed/', include('feed.urls', namespace="feed")),
	url(r'^admin/', include(admin.site.urls)),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from neighborhood.models import House, Neighborhood


class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
	house = models.ForeignKey(House, null=True)
	join_date = models.DateField(default=timezone.now)
	bio = models.TextField(max_length=1000, default='Default biography')
	member_status = models.CharField(max_length=100, default='neighbor')
	neighborhood_id = models.IntegerField(null=True)

	def is_board_member(self):
		return self.member_status == 'board-member'

	def __str__(self):
		return self.user.first_name + " " + self.user.last_name


class Activity(models.Model):
	id = models.AutoField(primary_key=True)
	date = models.DateTimeField(auto_now=True)
	activity_type = models.CharField(default='POST', max_length=30)
	user = models.ForeignKey(User)
	assoc_obj_id = models.IntegerField(default=-1)

accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect, HttpResponse

from .models import UserProfile
from .forms import UserForm
from neighborhood.models import Neighborhood, House
from feed.forms import AnnouncementForm


def user_login(request):
	"""
		---USER_LOGIN---
	:param request:
	"""
	if request.method == 'POST':
		# get username and password from input text
		username = request.POST['username_text']
		password = request.POST['password_text']

		# authenticate the credentials
		user = authenticate(username=username, password=password)

		# if we have a user the authentication was successful
		if user:
			# Is the account active? It could have been disabled.
			if user.is_active:
				# If the account is valid and active, we can log the user in.
				# We'll send the user back to the homepage.
				login(request, user)
				return HttpResponseRedirect('/neighborhood/home/')
			else:
				# An inactive account was used - no logging in!
				return HttpResponse("Your Neighbors account is disabled.")
		else:
			# Bad login details were provided. So we can't log the user in.
			return HttpResponse("The username and password you have entered do not match any account.")
	# The request is not a HTTP POST, so display the login form.
	# This scenario would most likely be an HTTP GET.
	else:
		# No context variables to pass to the template system.
		return render(request, 'accounts/login.html', {})


def demo_login(request):
	user = authenticate(username="demouser", password="demopass")
	if user:
		# Is the account active? It could have been disabled.
		if user.is_active:
			# If the account is valid and active, we can log the user in.
			# We'll send the user back to the homepage.
			login(request, user)
			return HttpResponseRedirect('/neighborhood/home/')
		else:
			# An inactive account was used - no logging in!
			return HttpResponse("Your Neighbors account is disabled.")


@login_required
def user_logout(request):
	"""
	---USER LOGOUT---
	:param request:
	"""
	logout(request)
	return HttpResponseRedirect('/')


def register_user(request):
	"""
	---REGISTER USER---
	:param request:
	"""
	registered = False
	if request.method == 'POST':
		# Using forms to collect new user data
		user_form = UserForm(request.POST)
		if user_form.is_valid():
			neighborhood = Neighborhood.objects.get(division_title=request.POST['neighborhood_text'])
			house = House.objects.filter(neighborhood=neighborhood,
										 permission_code=request.POST['perm_code_text'])
			if house:
				# We have checked that the forms are valid now save the user
				user = user_form.save()
				# Now we hash the password with the set_password method.
				# Once hashed, we can update the user object.
				user.set_password(user.password)
				user.save()
				user_profile = UserProfile(user=user, house=house)
				user_profile.save()
				return HttpResponseRedirect('/')
			else:
				# no house object was returned, invalid info provided
				return HttpResponse("The neighborhood and permission code you have entered do not match any existing neighborhood.")
	# Not a HTTP POST, so we render our form using two ModelForm instances.
	# These forms will be blank, ready for user input.
	else:
		user_form = UserForm()
	# Render the template depending on the context.
	return render(request, 'accounts/register.html', {'user_form': user_form,
													  'registered': registered})


"""
	---USER PROFILE---
"""
@login_required
def user_profile(request):
	user_prof = request.user.userprofile
	board_permissions = user_prof.is_board_member()
	announcement_form = AnnouncementForm()
	return render(request, 'accounts/profile.html', {'house': user_prof,
													 'board_permissions': board_permissions,
													 'announcement_form': announcement_form})

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="author" content="Tucker Stone">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Neighbors - Sign in</title>

    <!-- CSS -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">
</head>
<body>

<div class="demo-info">
    <p>What's Neighbors?</p>
    <form action="{% url 'accounts:demo_login' %}" method="POST">
        {% csrf_token %}
        <button>Take a tour</button>
    </form>
</div>

<div class="login-page">
    <h1>Nei<span style="color:#0a68f5">g</span>hbors</h1>
    <div class="form">
        <form class="login-form" action="{% url 'accounts:user_login' %}" method="post">
            {% csrf_token %}
            <input type="text" name="username_text" placeholder="username"/>
            <input type="password" name="password_text" placeholder="password"/>
            <button>login</button>
            <p class="message">Not registered? <a id="create-acct-btn" href="#">Create an account</a></p>
        </form>
    </div>
</div>
<script>$('#create-acct-btn').click(function(){alert("Account creations is currently disabled")});</script>
</body>
</html>

accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <title>Neighbors</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'neighborhood/css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>

<div class="nav">
    <h1 class="white-text">Neighbors</h1>
    <div class="options">
        <a class="btn btn-info" href="{% url 'neighborhood:home' %}"><strong>map</strong></a>
        <a class="btn btn-info" href="{% url 'neighborhood:status' %}"><strong>status</strong></a>
    </div>
    <div class="icons">
        <a id="account" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-user'></span>
        </a>
        <a id="account-menu" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-envelope'></span>
        </a>
        <a id="list" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-list'></span>
        </a>
        <a id="report" class='btn btn-default btn-circle btn-lg'>
            <span class='glyphicon glyphicon-alert'></span>
        </a>
    </div>
</div>


<div id="content" class="content">


    <div class="container">
        <div id="profile-pic">
            <p>Profile picture</p>
        </div>
        {% if board_permissions == True %}
            {#            <button id="announcement">Make Announcement</button>#}
            <button id="announcement" type="button" class="btn btn-info btn-lg"
                    data-toggle="modal" data-target="#myModal">
                Make Announcement
            </button>
        {% endif %}
        <h1 class="orange-text">{{ house.family_name }} Account</h1>
        <p>User: {{ house.user }}</p>
        <p>Neighborhood: {{ house.user.username }}</p>
        <p>Family Name: {{ house.family_name }}</p>
        <p>Join Date: {{ house.join_date }}</p>
        <p>Address: {{ house.address }}</p>
        <a href="{% url 'neighborhood:home' %}">Return</a>

        <div id="account-menu"></div>

        <div class="container">
            <!-- Modal -->
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <form method="post" action="{% url 'feed:announce' %}">
                            {% csrf_token %}
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">New Announcement</h4>
                            </div>
                            <div class="modal-body">
                                {{ announcement_form.as_p }}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>

</body>
</html>

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <h1>Register your home!</h1>
    {%  if registered %}
    <strong>thank you for registering!</strong>
    <a href="{% url 'accounts:user_login' %}">Return to login.</a><br />
    {% else %}
    <form id="user_form" action="{% url 'accounts:register_user' %}" method="post"
            enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        <input type="submit" name="submit" value="Register"/>
    </form>
    {%  endif %}
</body>
</html>

accounts/templates/accounts/user_profile.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Neighbors</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          crossorigin="anonymous">
{#    <link rel="stylesheet" type="text/css" href="{% static 'neighborhood/css/map_home.css' %}"/>#}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile.css' %}"/>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body><!--
<div class="nav">
    <h1 class="white-text">Neighbors</h1>
    <div class="options">
        <a class="btn btn-info" href="{% url 'neighborhood:home' %}"><strong>map</strong></a>
        <a class="btn btn-info" href="{% url 'neighborhood:status' %}"><strong>status</strong></a>
    </div>
    <div class="icons">
        <a id="account" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-user'></span>
        </a>
        <a id="messages" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-envelope'></span>
        </a>
        <a id="list" class='btn btn-default btn-circle btn-lg' href="{% url 'accounts:user_profile' %}">
            <span class='glyphicon glyphicon-list'></span>
        </a>
        <a id="report" class='btn btn-default btn-circle btn-lg'>
            <span class='glyphicon glyphicon-alert'></span>
        </a>
    </div>
</div>

<div id="report-container">
    <a id="cancel" class="btn btn-circle"><span class="glyphicon glyphicon-remove"></span></a>
    <div class='report'>
        <form action="{% url 'neighborhood:home' %}" method="POST">
            {% csrf_token %}
            {{ report_form.as_p }}
{#            <button id="close-report" class="btn btn-default">Close</button>#}
            <button id="submit-report" class="btn btn-default">Submit</button>
        </form>
    </div>
</div>-->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>

<div class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--

<div id="content" class="content">
    <div class="container">
        <div id="profile-pic">
            <p>Profile picture</p>
        </div>
        {% if board_permissions == True %}
        <button id="announcement">Make Announcement</button>
        {% endif %}
        <h1 class="orange-text">{{ house.family_name }} Account</h1>
        <p>User: {{ house.user }}</p>
        <p>Neighborhood: {{ house.user.username }}</p>
        <p>Family Name: {{ house.family_name }}</p>
        <p>Join Date: {{ house.join_date }}</p>
        <p>Address: {{ house.address }}</p>
        <a href="{% url 'neighborhood:home' %}">Return</a>

{#        <div id="messages">        </div>#}


    </div>
</div>





<div id = "announcement-form">
    <form method = "post" action = "">
        <p>Join TalkersCode And get Quick Access To Our
        Tutorials,Questions,Web Tricks And Many More</p>

        <a id="cancel" class="btn btn-circle"><span class="glyphicon glyphicon-remove"></span></a>
        <input type = "text" id = "login" placeholder = "Email Id" name = "uid">
        <input type = "password" id = "password" name = "upass" placeholder = "***">
        <input type = "submit" id = "dologin" value = "Login">
    </form>

</div>

<script src="{% static 'feed/announcement.js' %}"></script>-->

</body>
</html>