accounts/urls.py

from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^house/$', views.user_profile, name='user_profile'),
	url(r'^login/$', views.user_login, name='user_login'),
	url(r'^demo-login/$', views.demo_login, name='demo_login'),
	url(r'^logout/$', views.user_logout, name='user_logout'),
	url(r'^register/$', views.register_user, name='register_user'),
]

budget/urls.py

from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^new_budget/', views.create_budget, name='create'),
	url(r'^manage_budget/', views.manage_budget, name='manage'),
	url(r'^new_expense/', views.new_expense, name='new_expense'),
	url(r'^expense/(?P<expense_id>[0-9]+)/', views.expense_detail, name='expense_detail'),
	url(r'^expense/(?P<expense_id>[0-9]+)/', views.approve_expense, name='approve_expense'),
]

discussions/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^index/$', views.discussion_index, name='index'),
	url(r'^(?P<d_id>\d+)/$', views.discussion_detail, name='detail'),
	url(r'^new_discussion/$', views.new_discussion, name='new_discussion'),
]

feed/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^announce/$', views.make_announcement, name='announce'),
	url(r'^get-viewed/$', views.get_viewed, name='get-viewed'),
	url(r'^view-post/$', views.view_post, name='view-post'),
	url(r'^submit-post/$', views.submit_post, name='submit-post'),
	url(r'^refresh-feed/$', views.get_recent_posts_ajax, name='refresh-feed'),
	url(r'^get-announcements/$', views.get_announcements, name='get-announcements'),
]

neighborhood/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
	url(r'^home/$', views.neighborhood_home, name='home'),
	url(r'^status/$', views.neighborhood_status, name='status'),
	url(r'^index/$', views.index, name='index'),
	url(r'^details/$', views.neighborhood_details, name='details'),
	url(r'^get-neighborhoods/$', views.get_neighborhoods, name='get_neighborhoods'),
	url(r'^get-event/$', views.get_event, name='get_event'),
	url(r'^current-calendar/$', views.get_current_calendar, name='current_calendar'),
	url(r'^specific-calendar/$', views.get_specific_calendar, name='specific_calendar'),
	url(r'^new-event/$', views.new_event, name='new-event'),
]

neighbors/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from accounts.views import user_login

urlpatterns = [
	url(r'^$', user_login, name='index'),
	url(r'^neighborhood/', include('neighborhood.urls', namespace="neighborhood")),
	url(r'^account/', include('accounts.urls', namespace="accounts")),
	url(r'^budget/', include('budget.urls', namespace="budget")),
	url(r'^discussions/', include('discussions.urls', namespace="discussions")),
	url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^markers/', include('markers.urls', namespace="markers")),
	url(r'^feed/', include('feed.urls', namespace="feed")),
	url(r'^admin/', include(admin.site.urls)),
]

discussions/models.py
from django.db import models
from django.utils import timezone
import datetime


from accounts.models import User
from neighborhood.models import Neighborhood

# STATIC VARIABLES
MAX_DISCUSSION_NAME_LENGTH = 250


class Discussion(models.Model):
	id = models.AutoField(primary_key=True)
	title = models.CharField(
		max_length=MAX_DISCUSSION_NAME_LENGTH,
		default="Discussion Title", verbose_name="Discussion Title")
	description = models.TextField(
		default="Initial presentation of the Discussion Topic",
		verbose_name="Discussion Description")
	create_date = models.DateTimeField(default=timezone.now)
	creator = models.ForeignKey(User, null=True)
	neighborhood = models.ForeignKey(Neighborhood, null=True)
	last_modified = models.DateTimeField(default=timezone.now)

	def __str__(self):  # __unicode__ on Python 2
		return self.title

	def update_last_modified(self):
		self.last_modified = timezone.now()

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=5) <= self.create_date <= now

	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published Recently?'

	def as_dict(self):
		return {
			'title': self.title,
			'description': self.description,
			'last_modified': self.last_modified
		}


class Comment(models.Model):
	id = models.AutoField(primary_key=True)
	text = models.TextField(verbose_name="Comment Text")
	create_date = models.DateTimeField(default=timezone.now)
	creator = models.ForeignKey(User, null=True)
	discussion = models.ForeignKey(Discussion, null=True)

	def __str__(self):  # __unicode__ on Python 2
		return self.text

discussions/forms.py
from django import forms
from .models import Discussion, Comment


class DiscussionForm(forms.ModelForm):

	class Meta:
		model = Discussion
		fields = (
			'title',
			'description',
		)


class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = (
			'text',
		)

discussions/views.py
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
import json

from .models import Discussion, Comment
from .forms import DiscussionForm, CommentForm


@login_required
def discussion_index(request):
	"""
		---DISCUSSION INDEX---
	:param request:
	:return discussion_list:
	"""
	discussion_list = Discussion.objects.filter(neighborhood_id=request.session['neighborhood_id'])
	return render(request, 'discussions/index.html', {'discussion_list': discussion_list})


@login_required
def discussion_detail(request, d_id):
	"""
		---DISCUSSION DETAIL---
	:param request:
	:param d_id:
	:return discussion:
	:return discussion comments:
	:return comment_form:
	"""
	discussion = get_object_or_404(Discussion, pk=d_id)
	if request.method == 'POST':
		comment_form = CommentForm(request.POST)
		if comment_form.is_valid():
			comment = comment_form.save()
			comment.discussion = discussion
			comment.creator = request.user
			comment.save()
			discussion.update_last_modified()
		else:
			return HttpResponse("There was an ERROR when saving your comment")
	else:
		comment_form = CommentForm()
	comments = Comment.objects.filter(discussion=discussion)
	return render(request, 'discussions/detail.html', {'discussion': discussion,
													   'comments': comments,
													   'comment_form': comment_form})

@login_required
def new_discussion(request):
	"""
		---NEW DISCUSSION---
	:param request;
	:return discussion_form
	"""
	if request.method == 'POST':
		discussion_form = DiscussionForm(request.POST)
		if discussion_form.is_valid():
			discussion = discussion_form.save()
			discussion.neighborhood_id = request.session['neighborhood_id']
			discussion.creator = request.user
			discussion.save()
			return HttpResponseRedirect('/discussions/index/')
		else:
			return HttpResponse("There was an ERROR when saving your discussion topic")
	else:
		discussion_form = DiscussionForm()
	return render(request, 'discussions/new_discussion.html', {'discussion_form': discussion_form})


@login_required
def get_recent_discussions(request):
	"""
		Return the 5 most recently modified discussions
	:param request:
	:return:
	"""
	n_id = request.session['neighborhood_id']
	recent_discussion_dict = [dis for dis in Discussion.objects
									 .filter(neighborhood_id=n_id)
									 .order_by('-last_modified')[:5]]
	return HttpResponse(json.dumps({'disc_list': recent_discussion_dict}), content_type='application/json')

discussions/templates/discussions/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Neighbors</title>
</head>
<body>
    <h1>{{ discussion.title }}</h1>
    <p>{{ discussion.description }}</p>
    {% for comment in comments %}
        <p>{{ comment.creator }} Said:<br />
        {{ comment.text }}<br />
        on: {{ comment.create_date }}</p>
    {% endfor %}

    <p>
    <form id="comment_form" action="{% url 'discussions:detail' discussion.id %}" method="post">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" name="submit" value="Post Comment">
    </form>
    </p>

    <a href="{% url 'discussions:index' %}">Return to Discussion Board</a><br />

</body>
</html>

discussions/templates/discussions/index.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'neighborhood/css/home.css' %}" />
    <meta charset="UTF-8">
    <title>Neighbors</title>
</head>
<body>

    <div class="jumbotron">
        <div class="container">
            <h1>Welcome to the Neighborhood!</h1>
            <p>{{ neighborhood.division_title }} Division</p>
        </div>
    </div>

    <div class="nav">
        <div class="container">
            <ul class="nav nav-pills">
                <li><a href="{% url 'neighborhood:neighborhood_home' %}">Home</a></li>
                <li><a class="active" href="{% url 'polls:index' %}">Polls</a></li>
				<li><a href="{% url 'discussions:index' %}">Discussions</a></li>
                <li><a href="{% url 'budget:manage' %}">Budget</a></li>
                <li><a href="{% url 'neighborhood:about' %}">About Neighbors</a></li>
                <li><a href="{% url 'accounts:user_profile' %}">Manage Account</a></li>
                <li><a href="{% url 'accounts:user_logout' %}">Sign out</a></li>
            </ul>
        </div>
    </div>

    <div class="content">
        <div class="container">
            <h1>Discussion Board</h1>
            {% for discussion in discussion_list %}
                <a href="{% url 'discussions:detail' discussion.id %}"><h3>{{ discussion.title }}</h3></a>
                <p>Creator ID: {{ discussion.create_date }}
                    Date Created: {{ discussion.create_date }}</p>
                <p></p>
            {% endfor %}


            <a href="{% url 'discussions:new_discussion' %}"><input type="button" value="New Discussion"></a><br />
        </div>
    </div>

    <div class="footer">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<h3>About</h3>
					<p>Info/links regarding Neighbors information.</p>
				</div>
				<div class="col-md-4">
					<h3>Contact</h3>
					<p>Info/links for contacting Neighbors peeps</p>
				</div>
				<div class="col-md-4">
					<h3>Help</h3>
					<p>Help and FAQ shit.</p>
				</div>
			</div> <!-- end row -->
		</div> <!-- end container -->
	</div> <!-- end footer -->

</body>
</html>

discussions/templates/discussions/new_discussion.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Neighbors</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'neighborhood/css/map_home.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'discussions/style.css' %}"/>
</head>
<body>

<div class="nav">
    <h1 class="white-text">Neighbors</h1>
    <div class="options">
        <a class="btn btn-info" href="{% url 'neighborhood:home' %}"><strong>map</strong></a>
        <a class="btn btn-info" href="{% url 'neighborhood:status' %}"><strong>status</strong></a>
    </div>
    <a id="account" class="btn btn-default" href="{% url 'accounts:user_profile' %}">account</a>
</div>
<div class="content">
    <div class="container col-md-2 col-md-offset-5">
        <h1 class="orange-text">New Discussion</h1>
        <form id="discussion_form" action="{% url 'discussions:new_discussion' %}" method="post">
            {% csrf_token %}
            {{ discussion_form.as_p }}
            <input class='btn btn-default' type="submit" name="submit" value="Post Discussion"/>
        </form>
        <a href="{% url 'neighborhood:status' %}">Return</a>
    </div>
</div>

</body>
</html>